file_upload/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning.urls')),
    path('file/', include('file_upload.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

learning/urls.py
from django.urls import path
from .views import home, one_to_many, export_csv, export_data

app_name='learning'

urlpatterns = [
     path('', home, name='index'),
     path('one_to_many/', one_to_many, name='one_to_many'),
     path('export/', export_csv, name='export_csv'),
     path('export-data/', export_data, name='export_data'),
]

textutils/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('analyze', views.analyze, name='analyze'),

    # path('removepunc', views.removepunc, name='rempun'),
    # path('capitalizefirst', views.capfirst, name='capfirst'),
    # path('newlineremove', views.newlineremove, name='newlineremove'),
    # path('spaceremove', views.spaceremove, name='spaceremove'),
    # path('charcount', views.spaceremove, name='charcount')
]

file_upload/models.py
from django.db import models

# Create your models here.

learning/models.py
from django.db import models

# Create your models here.

learning/models/one_to_many.py
'''
(c) learning 2020

Purpose : Learning one to many relation
'''

from django.db import models

class Mother(models.Model):
    first_name = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name

class Son(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mother = models.ForeignKey(Mother,null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return self.first_name

learning/models/report.py
'''
(c) learning 2020

Purpose : Learning one to many relation
'''

from django.db import models

class Detail(models.Model):
    name = models.CharField(max_length=100,unique=True)
    type = models.CharField(max_length=100)
    percentage = models.IntegerField()

    def __str__(self):
        return str(self.name)

class Status(models.Model):
    started_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25)
    detail = models.ForeignKey(Detail, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.detail)

learning/forms/one_to_many.py
from django import forms
from ..models import Mother, Son

class UploadSonForm(forms.ModelForm):
	class Meta:
		model = Son
		fields = ('first_name','last_name')

file_upload/views.py
from django.shortcuts import render

# Create your views here.

learning/views.py
# Create your views here.

learning/views/export.py
'''
(c) learning 2020

Purpose : Learning one to many relation
Ideas : https://dev.to/coderasha/how-to-export-import-data-django-package-series-3-39mk
'''
import csv
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse

from ..models import Status, Detail, Son
from ..resources import SonResource

def export_csv(request):
	'''
	Dump model data in a csv file
	'''
	date = str(datetime.now().strftime('%Y_%m_%d_%H_%M_%S'))
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment;filename="Report_{}.csv"'.format(str(date))
	writer = csv.writer(response)
	writer.writerow(['ID', 'Name', 'Type', 'Pencentage','started_time','status'])

	status_fields = [field.name for field in Status._meta.concrete_fields]
	detail_fields = ['detail__{}'.format(field.name) for field in Detail._meta.concrete_fields]
	all_fields = ['id', 'detail__name', 'detail__type', 'detail__percentage','started_time', 'status']
	training_report_list = list(Status.objects.values_list(*all_fields))

	for report in training_report_list:
		writer.writerow(report)
	return response

def export_data(request):
	'''
	Get parameter from user and dump data into that particular parameter
	'''
	date = str(datetime.now().strftime('%Y_%m_%d_%H_%M_%S'))
	if request.method == "POST":
		# get selected option from form
		file_format = request.POST['file-format']
		son_resources = SonResource()
		dataset = son_resources.export()
		if file_format == 'CSV':
			response = HttpResponse(dataset.csv, content_type="text/csv")
			response['Content-Disposition'] = 'attachment; filename="Report_{}.csv"'.format(str(date))
			return response
		elif file_format == 'JSON':
			response = HttpResponse(dataset.json, content_type='application/json')
			response['Content-Disposition'] = 'attachment; filename="Report_{}.csv"'.format(str(date))
			return response
		elif file_format == 'XLS (Excel)':
			response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
			response['Content-Disposition'] = 'attachment; filename="Report_{}.csv"'.format(str(date))
			return response
	return render(request, 'learning/export_data.html')

learning/views/index.py
'''
(c) learning 2020

Purpose: This is the file where we can handle home page operation

'''
from django.shortcuts import render
from django.shortcuts import HttpResponse

# Create your views here.
def home(request):
    return render(request,"learning/index.html")

learning/views/one_to_many.py
'''
(c) learning 2020

Purpose: learn one to many relationship

'''
from django.shortcuts import render
from django.shortcuts import HttpResponse

from ..models import Mother, Son
from ..forms import UploadSonForm

# Create your views here.
def one_to_many(request):
    if request.method == 'POST':
        form = UploadSonForm(request.POST)
        if form.is_valid():
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            mother_inst, created = Mother.objects.get_or_create(first_name=request.POST.get('mother'))
            son = Son(first_name=first_name,last_name=last_name,mother_id=mother_inst.id)
            son.save()
            return render(request,"learning/index.html")
    return render(request,"learning/one_to_many.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Learning App</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}"/>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
{% include 'header.html' %}

<div class="content">
{% block content %}{% endblock %}
</div>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<footer class="page-footer font-small bg-dark">
    <div class="footer-copyright text-center py-3">© 2020 Learning:
        <a href="#"> learning.in</a>
    </div>
</footer>

templates/header.html
<header>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Export_data
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'learning:export_csv' %}">Export_CSV</a>
                  <a class="dropdown-item" href="{% url 'learning:export_data' %}">Export_with_option</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">contact</a>
            </li>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'learning:one_to_many' %}">One to Many</a>
              <a class="dropdown-item" href="#">Many to Many</a>
              <a class="dropdown-item" href="#">Django Channel</a>
            </div>
          </li>

        </ul>
    </nav>
</header>

templates/learning/export_data.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h3>Export Data</h3>
<p>exporting from database</p>
<form action="{% url 'learning:export_data' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Please select format of file.</p>
    <select name="file-format" class="form-control my-3">
        <option selected>Choose format...</option>
        <option>CSV</option>
        <option>JSON</option>
        <option>XLS (Excel)</option>
      </select>
    <button class="btn btn-primary" type="submit">Export</button>
  </form>
  <a href="{% url 'learning:index' %}">Return Home View</a>
{% endblock %}

templates/learning/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p> This is my home page </p>
{% endblock %}

templates/learning/one_to_many.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container p-3">
    <form action="{% url 'learning:one_to_many' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleFormControlInput1">First name</label>
            <input type="text" name="first_name" class="form-control" id="exampleFormControlInput1" placeholder="Archana">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Last name</label>
            <input type="text" name="last_name" class="form-control" id="exampleFormControlInput1" placeholder="wangade">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Mother Name</label>
            <input type="text" name="mother" class="form-control" id="exampleFormControlInput1" placeholder="wangade">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Submit</button>
    </form>
</div>
{% endblock %}